Repository serverless/dashboard-plugin, pull requests merged in 2020-01, with the labels that each got.

#339 PLAT-2171 Fix standalone support
  lib/plugin.js
  package.json
Labels: bug

#347 `param` and `output` CLI commands
  integration-testing/wrapper.test.js
  lib/deployProfile.js
  lib/deployProfile.test.js
  lib/interactiveCli/index.js
  lib/interactiveCli/index.test.js
  lib/interactiveCli/register.test.js
  lib/interactiveCli/set-app.js
  lib/interactiveCli/set-app.test.js
  lib/outputCommand.js
  lib/outputCommand.test.js
  lib/paramCommand.js
  lib/paramCommand.test.js
  lib/plugin.js
  lib/plugin.test.js
  lib/resolveOutput.js
  lib/resolveOutputs.js
  lib/resolveParams.js
  lib/throwAuthError.js
  lib/variables.js
  lib/variables.test.js
  package.json
  test/fixtures/aws-loggedin-monitored-service/.serverlessrc
  test/fixtures/aws-loggedin-monitored-service/serverless.yml
  test/fixtures/aws-loggedin-noapp-service/.serverlessrc
  test/fixtures/aws-loggedin-noapp-service/serverless.yml
  test/fixtures/aws-loggedin-service/.serverlessrc
  test/fixtures/aws-loggedin-service/serverless.yml
  test/fixtures/aws-loggedin-wrongapp-service/.serverlessrc
  test/fixtures/aws-loggedin-wrongapp-service/serverless.yml
  test/fixtures/aws-loggedin-wrongorg-service/.serverlessrc
  test/fixtures/aws-loggedin-wrongorg-service/serverless.yml
  test/fixtures/aws-monitored-service/serverless.yml
  test/fixtures/aws-service/.serverlessrc
  test/fixtures/aws-service/serverless.yml
  test/fixtures/non-aws-service/serverless.yml
  test/fixtures/non-supported-runtime-service/serverless.yml
Labels: enhancement

#349 Don't barf when boto error doesn't have a response
  sdk-py/serverless_sdk/__init__.py
Labels: bug

#355 Downgrade `semver` to v6
  package.json
Labels: dependencies
