Repository serverless/dashboard-plugin, pull requests merged in 2020-08, with the labels that each got.

#460 Configure "app" and "org" schemas for validation on Framework side
  lib/plugin.js
Labels: enhancement

#461 DEP: Switch to cross-fetch instead of isomorphic-fetch
  lib/test/runTest.js
  lib/test/runTest.test.js
  package.json
Labels: dependencies

#466 Report unsupported region meaningfully
  lib/plugin.js
  lib/plugin.test.js
Labels: bug

#478 Deprecate safeguards
  lib/plugin.js
  lib/safeguards/index.js
Labels: deprecation, enhancement

#484 Remove "dev" command
  lib/plugin.js
  lib/plugin.test.js
Labels: breaking

#485 Improve version update notifications
  lib/plugin.js
Labels: bug
