Repository serverless/dashboard-plugin, pull requests merged in 2020-12, with the labels that each got.

#517 Recognize `functions[].image` configurations
  lib/wrap.js
  lib/wrap.test.js
Labels: enhancement

#522 Remove custom.safeguards schema validation
  README.md
  examples/safeguards-example-service/handler.js
  examples/safeguards-example-service/policies/limit-ddb-capacity/index.js
  examples/safeguards-example-service/policies/no-wild-cors.js
  examples/safeguards-example-service/policies/stage-in-table-name.js
  examples/safeguards-example-service/serverless.yml
  integration-testing/README.md
  lib/deployProfile.js
  lib/deployProfile.test.js
  lib/deployment/parse.js
  lib/plugin.js
Labels: bug

#524 feature(Providers): Detect when a user supplies a parameterized input…
  lib/deployProfile.js
  lib/deployProfile.test.js
Labels: deprecation, enhancement

#526 bugfix: Null check deploymentProfile
  lib/deployProfile.js
  lib/providersIntegration.test.js
Labels: bug
